spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_AUTH_DB}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: ${JWT_SECRET}