server:
  port: 8080 # Porta interna do container (mapeada para 8083 no compose)

spring:
  application:
    name: assignment-service
  data:
    mongodb:
      uri: mongodb://root:${MONGO_INIT_PASSWORD}@localhost:27017/assignments?authSource=admin

jwt:
  secret: ${JWT_SECRET}