server:
  port: 8083

spring:
  application:
    name: assignment-service
  data:
    mongodb:
      # Tenta usar a variável do Docker; se não existir (como na IDE), faz fallback para o localhost
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${MONGO_INIT_USER}:${MONGO_INIT_PASSWORD}@localhost:27017/assignments?authSource=admin}

jwt:
  secret: ${JWT_SECRET}