server:
  port: 8083

spring:
  application:
    name: assignment-service

  datasource:
    url: jdbc:mysql://localhost:3309/${MYSQL_ASSIGNMENT_DB}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.edu.academic_plataform: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

jwt:
  secret: ${JWT_SECRET}
