name: API-Tests

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'services/academic-service/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'services/academic-service/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 1. Clonar o repositório
        uses: actions/checkout@v3

      - name: 2. Configurar o Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 3. Instalar dependências
        working-directory: services/academic-service
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn sqlalchemy pymysql pydantic pydantic-settings pytest httpx

      - name: 4. Rodar os testes automatizados
        working-directory: services/academic-service
        env:
          DATABASE_URL: "mysql+pymysql://root:root@127.0.0.1:3306/test_db"
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_ACADEMIC_DB: "test_db"
        run: |
          pytest